try:
    from def_exception import ExperimentError, DataLoadError, TranscribeError, TokenizerInitWarning
except Exception:
    class ExperimentError(Exception): ...
    class DataLoadError(ExperimentError): ...
    class TranscribeError(ExperimentError): ...
    class TokenizerInitWarning(Warning): ...
